### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Rain-L25** [BinaryLip/ScheduleViewer#1]
Hello, I really like your Schedule Viewer Mod, so I made a Chinese translation for it. I'm not a programmer and hardly use Github, so I'm not sure where to upload the translation file. I've attached it here [zh.json](https://github.com/BinaryLip/ScheduleViewer/files/13787683/zh.json), and you can place the translated file into your MOD.
While using the mod after translation, I noticed a few flaws, maybe you could optimize it:

1. My translated fields are invalid for the options.
![image](https://github.com/BinaryLip/ScheduleViewer/assets/135552654/f0ff7e8c-e54c-46b1-bcd5-82f36f540e5d)
2. For some locations that the game itself does not localize (FarmHouse)
![image](https://github.com/BinaryLip/ScheduleViewer/assets/135552654/727c4485-3955-4369-89ba-27202e1f4df2)
or for mods that add new maps (Ridgeside Village (already localized))
![image](https://github.com/BinaryLip/ScheduleViewer/assets/135552654/995c57de-009f-4ecb-acad-9c9b2fc5b556)
the displayed map names in Schedule Viewer seem out of place. 
Even though I'm not proficient in programming, I know this isn't caused by your MOD. 
I attempted to directly alter a map's string display through another mod, which did solve the issue, but it was a bit cumbersome. 
![image](https://github.com/BinaryLip/ScheduleViewer/assets/135552654/8348d07e-ed86-4702-89f8-409da5fdc198)
Perhaps, in the configuration, you could allow players to add and define some strings, like "FarmHouse: Farm House". When the value for an NPC's location is <FarmHouse>, it would display the translated name <Farm House>. This is just an idea of mine; I'm not sure if it's correct or implementable.

Wishing you a wonderful life ahead!

**Comment by BinaryLip** [comment]
Hi, thanks so much for doing this!!

1. I'm looking into this right now. I think I've tracked down the cause, just need to figure out a solution lol.
2. Yeah, that's a known issue. I don't have a good solution right now, but I'm hopeful that with the changes coming in SDV 1.6 I can provide better display names for custom locations added by other mods. I'm going to add a localization option explicitly for Farmhouse.

Would 农家 be a correct translation for Farmhouse?
Could you also link your nexus mods profile URL? I'd like to credit you for the translations on the mod page :)

**Comment by Rain-L25** [comment]
I'm very happy to have received your response!
Farmhouse would be better translated as 农场房屋
My nexus mods profile URL is https://www.nexusmods.com/users/102031818
