### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by YossshY** [BinaryLip/ScheduleViewer#2]
Hello, here is the French translation for your mod.

[fr.json](https://github.com/BinaryLip/ScheduleViewer/files/14575694/fr.json)

Options :

![Option1_Planning](https://github.com/BinaryLip/ScheduleViewer/assets/20166589/611ee02a-9ad6-4cee-8832-52afb82a84a4)
![Option2_Planning](https://github.com/BinaryLip/ScheduleViewer/assets/20166589/834e183c-b13b-420f-b49d-c82093531b15)

Schedule View :

![Planning1](https://github.com/BinaryLip/ScheduleViewer/assets/20166589/d9edeccd-fb22-4602-9fba-65d2bb9bf595)
![Planning2](https://github.com/BinaryLip/ScheduleViewer/assets/20166589/ac17b976-36b2-45cf-b09b-ba4de4a086fb)

I made some modifications so that the text does not exceed the fields but I have a problem with "can gift today?" in French "Peut recevoir un cadeau aujourd'hui" is way too long...

it would not be possible to invert the Yes/No value? using “Gifted today?” in French “Cadeau recu?”.

Thank you for your mod and have a nice day.

**Comment by YossshY** [comment]
Here are the modified json in case you know how to reverse the YES/NO value

[default.json](https://github.com/BinaryLip/ScheduleViewer/files/14575997/default.json)

> I modified:
> 
> Line 29: “Can gift today?” by "Gifted today?"
> Line 40: "Sebastion's Room" by "Sebastian's Room" to correct the first name
> Line 43: "Witch's Swamp'" by "Witch's Swamp" to remove the apostrophe (') after "Swamp"

[fr.json](https://github.com/BinaryLip/ScheduleViewer/files/14576003/fr.json)

> I modified:
> Line 29: “Peut recevoir un cadeau aujourd'hui?” by "Cadeau reçu?"

Have a nice day.

**Comment by BinaryLip** [comment]
Hi, thank you so much for providing the French translation and thanks for catching those English language mistakes too! 

I just switched "Can gift today?" out for "Gifted today?". I renamed that property from `schedule_details_page.can_give_gift` to `schedule_details_page.gifted_today.header` and added one more property `schedule_details_page.gifted_today.weekly_limit` as well if you could provide a translation for that too I'd appreciate it!
![image](https://github.com/BinaryLip/ScheduleViewer/assets/16822674/6adee889-7bcc-437a-8fa7-75dbd0d222a4)

Github is giving me a 404 error when trying to download the fr.json file. Could you paste the contents of the file in a comment instead?

**Comment by YossshY** [comment]
Hi, ok no problem here are the requested modifications ;-)

fr.json:

{
  "config.title.general": "Options Générales:",
  "config.option.show_schedule_key.name": "Touche pour afficher le Planning",
  "config.option.disable_hover.name": "Cacher les détails au survol",
  "config.option.disable_hover.description": "Masquer les informations sur les carreaux, la direction et l'animation d'infos au survol.",
  "config.option.use_large_font.name": "Utilisez une police plus grande",
  "config.option.use_large_font.description": "Utilisez une police plus grande sur la page Détails du Planning. (Si activé, le texte peut être coupé en fonction du nom de l'emplacement.)",
  "config.title.filter_sort": "Options de filtrage et de tri:",
  "config.option.sort_options.name": "Ordre de tri des PNJ",
  "config.option.sort_options.description": "L'ordre dans lequel les PNJ doivent être triés lors de l'affichage de leur planning.",
  "config.option.sort_options.option_0": "Alphabétique Ascendant",
  "config.option.sort_options.option_1": "Alphabétique Descendant",
  "config.option.sort_options.option_2": "Coeurs ascendants",
  "config.option.sort_options.option_3": "Coeurs descendants",
  "config.option.only_show_met_npcs.name": "Masquer les PNJ non rencontrés",
  "config.option.only_show_met_npcs.description": "Masquer les PNJ auxquels vous n'avez jamais parlé auparavant dans la liste.",
  "config.option.only_show_socializable_npcs.name": "Masquer les PNJ non socialisables",
  "config.option.only_show_socializable_npcs.description": "Masquer les PNJ non socialisables (ex : Gunther ou Sandy avant que le bus ne soit réparé) dans la liste.",
  "error.mismatch_mods": "Avertissement! Vous et le joueur hôte avez des mods/versions de mod différents qui peuvent affecter l'exactitude des plannings. Voir le journal SMAPI pour plus de détails.",
  "error.mismatch_game_version": "Avertissement! Vous et le joueur hôte disposez de versions de jeu différentes, ce qui peut affecter l'exactitude des plannings.",
  "location_hover_text": "Sur le carreau ({{x}}, {{y}}) dirigé vers {{facingDirection}}",
  "ignoring_schedule_today": "Planning du jour ignoré. Emplacement actuel:",
  "not_following_schedule_today": "Pas de planning pour aujourd'hui. Emplacement actuel:",
  "facing_direction_0": "le haut",
  "facing_direction_1": "la droite",
  "facing_direction_2": "le bas",
  "facing_direction_3": "la gauche",
  "farmhouse": "Ferme",
  "schedule_details_page.header": "Planning",
  "schedule_details_page.gifted_today.header": "Cadeau reçu?",  
  "schedule_details_page.gifted_today.weekly_limit": "Limite hebdo atteinte",
  "schedule_details_page.current_location": "Emplacement",
  "location_names.Club": "Casino",
  "location_names.HarveyRoom": "Chambre d'Harvey",
  "location_names.IslandEast": "Île Gingembre Est",
  "location_names.IslandHut": "Hutte",
  "location_names.IslandNorth": "Île Gingembre Nord",
  "location_names.IslandSouth": "Île Gingembre Sud",
  "location_names.IslandWest": "Île Gingembre Ouest",
  "location_names.LeoTreeHouse": "Maison dans l'arbre",
  "location_names.SandyHouse": "Oasis",
  "location_names.SebastianRoom": "Chambre de Sébastian",
  "location_names.SkullCave": "Caverne du Crâne",
  "location_names.Sunroom": "Véranda de Caroline",
  "location_names.WitchSwamp": "Marais de la sorcière",
  "location_names.WitchWarpCave": "Hutte de la sorcière"
}

Have a nice day.

**Comment by BinaryLip** [comment]
Awesome, thanks! I'll get those added for the 1.6 release. 

How would you like to be credited for the translation? I'm happy to link to your GitHub, Twitter, and/or Nexus Mods account.

**Comment by YossshY** [comment]
You can just put my username YoshY for the credit ;-)
